version: "3"
services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
