---
development: &default
  adapter: postgresql
  encoding: unicode
  database: edukasyonph_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: edukasyonph_test

production:
  <<: *default
  database: edukasyonph_production
